import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/app/components/navigation/sidebar";
import "./globals.css";
// import Quiz from "./pages/quiz";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex gap-5">
          <Sidebar />
          <div className={inter.className}>{children}</div>
          {/* <Quiz/> */}
        </div>
      </body>
    </html>
  );
}